name: "More-Behaviors"

web: "[clientcide.com](http://clientcide.com)"

description: "Behavior filters for MooTools More"

license: "MIT License"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

sources:
  - "Source/Fx/Behavior.FxAccordion.js"
  - "Source/Forms/Behavior.FormRequest.js"
  - "Source/Forms/Behavior.FormValidator.js"
  - "Source/Interface/Behavior.HtmlTable.js"
  - "Source/Forms/Behavior.OverText.js"
