name: "More-Behaviors"

web: "[mootools.net](http://mootools.net)"

description: "Behavior filters for MooTools More"

license: "[MIT License](http://mootools.net/license.txt)"

copyright: "&copy; [MooTools](http://mootools.net)"

authors: "[The MooTools development team](http://mootools.net/developers)"

sources:
  - "Source/Fx/Behavior.FxAccordion.js"
  - "Source/Forms/Behavior.FormRequest.js"
  - "Source/Forms/Behavior.FormValidator.js"
  - "Source/Interface/Behavior.HtmlTable.js"
  - "Source/Forms/Behavior.OverText.js"
