name: "More-Behaviors-Tests"

description: "Tests for the Behavior filters for MooTools More"

license: "MIT License"

copyright: "&copy; [Aaron Newton](http://clientcide.com)"

authors: "[Aaron Newton](http://clientcide.com)"

sources:
  - "Fx/Behavior.FxAccordion.js"
  - "Forms/Behavior.FormRequest.js"
  - "Forms/Behavior.FormValidator.js"
  - "Forms/Behavior.OverText.js"
  - "Interface/Behavior.HtmlTable.js"
  - "Drag/Behavior.Resizable.js"
  - "Drag/Behavior.Sortable.js"
